### ISSUE TITLE
Lacking Information

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Luke100000/ImmersivePaintings#2]
I don't understand how to make a resource pack I don't understand how to import from online - when I imported from images it was ridiculously huge - does the game not scale it down?

Important needed information - what is the recommended image size? What level of detail - I love this  mod but I have legit no idea how to make it work for me.

**Comment by Luke100000** [comment]
I will create a docu for datapacks soon.

When importing, the mod tries to match the aspect ratio, but in the end you need to specify width and height yourself if you do not agree with the guess (left side, top).

Recommended image size depends on the size you want ingame, but usually every image works as ingame textures are usually <512px.

Level of detail is a term in computer graphics where the resolution decreases after a certain distance since you can't see the difference anyways, to save performance. Nothing you need to worry about yourself.

Just in case, the documentation for the config is here https://github.com/Luke100000/ImmersivePaintings/wiki/Config

**Comment by Luke100000** [comment]
https://github.com/Luke100000/ImmersivePaintings/wiki/Custom-Paintings
