### ISSUE TITLE
1.20.4 NeoForge?

### ISSUE THREAD

**Issue by DinosaurGuy1997** [Luke100000/ImmersivePaintings#84]
Here's hoping it wouldn't be too hard to update it to this version...

;w;

**Comment by Luke100000** [comment]
Definitely no 1.20.4, please use 1.20.1

**Comment by DinosaurGuy1997** [comment]
At least tell us why.

**Comment by Luke100000** [comment]
Because I don't want to :) 1.20.4 is just a crippled, barely used version of 1.21. It would be a waste of time to support it.

**Comment by DinosaurGuy1997** [comment]
Rude. Mekanism's last update was on 1.20.4, so your logic is flawed here.

**Comment by Luke100000** [comment]
> Rude. Mekanism's last update was on 1.20.4, so your logic is flawed here.

Yea, and guess what, it's barely used. Roughly 5% as much as 1.20.1 and 15% as 1.21. Even Neoforge themselves highly advise not using pre 1.21 versions.

**Comment by DinosaurGuy1997** [comment]
Then explain why all the mods I use are on 1.20.4 and not 1.21

**Comment by Luke100000** [comment]
> Then explain why all the mods I use are on 1.20.4 and not 1.21

Because 1.21 is a shitton of work? Just because there IS a version doesn't mean there is any reason to put work into it. There is no downside in using 1.20.1, so why would I spend hours porting to an effectively dead version. If you have that free time to spare, port it yourself. Otherwise use 1.20.1 like a sane soul.
